# Generated by Django 5.2.6 on 2025-09-24 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_estoque', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_locacao', models.DateField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locacoes', to='cadastro.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemLocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.equipamento')),
                ('locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cadastro.locacao')),
            ],
        ),
    ]
