# Generated by Django 5.2.6 on 2025-09-24 06:36

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_locacao_data_devolucao_alter_locacao_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='quantidade_estoque',
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='itemlocacao',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cliente'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='data_devolucao',
            field=models.DateField(default=datetime.datetime(2025, 9, 25, 6, 35, 7, 786170, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='data_locacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='aberta', max_length=20),
        ),
    ]
