# Generated by Django 5.2.6 on 2025-09-17 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_locacao', models.DateField(verbose_name='Data da Locação')),
                ('data_devolucao', models.DateField(verbose_name='Data da Devolução')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('entregue', models.BooleanField(default=False, verbose_name='Material Entregue')),
                ('devolvido', models.BooleanField(default=False, verbose_name='Material Devolvido')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cliente', verbose_name='Cliente')),
                ('equipamentos', models.ManyToManyField(to='cadastro.equipamento')),
            ],
            options={
                'verbose_name': 'Locação',
                'verbose_name_plural': 'Locações',
            },
        ),
    ]
